export const HOME_PAGE = "home_page"
export const DAILY_ACTIVE = "daily_active"
export const CLASSIFY_CATEGORYS = "classify_categorys"
export const GOODS_LIST = "goods_list"
export const BRAND_LIST = "brand_list"
